version: '2'
services: 
    nginx:
        build: ./nginx
        image: vivo/mvapp/nginx:1.0
        links:
            - rest1:rest1
            - rest2:rest2
        ports:
            - "80:80"

    rest1:
        build: ./soap
        image: vivo/mvapp/rest:1.0
        extra_hosts: 
            - alsb3-soa:10.129.165.52
        links:
            - redis
            - queue
        depends_on: 
            - queue
        ports:
            - "8080"
        environment: 
            AMQP_URL: 'ampq://queue'
            CONTAINER_ID: 'rest1'

    rest2:
        build: ./soap
        image: vivo/mvapp/rest:1.0
        extra_hosts: 
            - alsb3-soa:10.129.165.52
        links:
            - redis
            - queue
        depends_on: 
            - queue
        ports:
            - "8080"
        environment: 
            AMQP_URL: 'ampq://queue'
            CONTAINER_ID: 'rest2'

    api:
        build: ./api
        image: vivo/mvapp/api:1.0
        links:
            - queue
        depends_on: 
            - queue
        environment: 
            AMQP_URL: 'ampq://queue'

    redis:
        image: redis
        ports:
            - "6379:6379"
    queue:
        image: wurstmeister/kafka
        hostname: "queue"
