version: '2'
services: 
    nginx:
        build: ./nginx
        image: vivo/mvapp/nginx:1.0
        links:
            - rest1:rest1
            - rest2:rest2
        ports:
            - "80:80"

    rest1:
        build: 
            context: ./simple-rest
            args:
                PROXY: ${PROXY}
        image: simples-rest:latest
        links:
            - redis
            - queue
        depends_on: 
            - queue
        ports:
            - "8080"
        environment: 
            AMQP_URL: 'ampq://queue'
            CONTAINER_ID: 'rest1'

    rest2:
        build: 
            context: ./simple-rest
            args:
                PROXY: ${PROXY}
        image: simple-rest:latest
        links:
            - redis
            - queue
        depends_on: 
            - queue
        ports:
            - "8080"
        environment: 
            AMQP_URL: 'ampq://queue'
            CONTAINER_ID: 'rest2'
                
    queue:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
        environment: 
            - RABBITMQ_HIPE_COMPILE=1
        hostname: "queue"
