version: '2'
services: 
    haproxy:
        image: dockercloud/haproxy
        links:
            - rest
        volumes:
           - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:80"

    rest:
        build: 
            context: ./soap
            args:
                PROXY: ${PROXY}  
        image: vivo/mvapp/rest:latest
        extra_hosts: 
            - alsb3-soa:10.129.165.52
        links:
            - redis
            - queue
        depends_on: 
            - queue
        ports:
            - "8080"
        environment: 
            QUEUE_PORT: '15672'
            QUEUE_URL: 'ampq://queue'
            CONTAINER_ID: 'rest1'

    api:
        build: 
            context: ./api
            args:
                PROXY: ${PROXY}
        image: vivo/mvapp/api:1.0
        links:
            - queue
        depends_on: 
            - queue
        environment:
            QUEUE_PORT: '15672' 
            QUEUE_URL: 'ampq://queue'

    redis:
        image: redis
        ports:
            - "6379:6379"
    
    queue:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
        environment: 
             - RABBITMQ_HIPE_COMPILE=1
        hostname: "queue"